"""add_analytics_tables

Revision ID: fa8bbcb83c34
Revises: 8c2cf1d358be
Create Date: 2026-05-28 05:03:39.910600
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8bbcb83c34'
down_revision: Union[str, None] = '8c2cf1d358be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('metrics', sa.Text(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ai_provider', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_report_type_date', 'ai_reports', ['tenant_id', 'report_type', 'date'], unique=True)
    op.create_index(op.f('ix_ai_reports_tenant_id'), 'ai_reports', ['tenant_id'], unique=False)
    op.create_table('participant_daily_stats',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('first_entry', sa.DateTime(), nullable=True),
    sa.Column('last_leave', sa.DateTime(), nullable=True),
    sa.Column('total_duration_minutes', sa.Float(), nullable=False),
    sa.Column('enter_count', sa.Integer(), nullable=False),
    sa.Column('short_stay', sa.Boolean(), nullable=False),
    sa.Column('late_entry', sa.Boolean(), nullable=False),
    sa.Column('night_entry', sa.Boolean(), nullable=False),
    sa.Column('consecutive_late_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participant_daily_stats_tenant_id'), 'participant_daily_stats', ['tenant_id'], unique=False)
    op.create_index('ix_pds_tenant_date_name', 'participant_daily_stats', ['tenant_id', 'date', 'name'], unique=True)
    op.create_table('risk_scores',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('risk_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_dedup', 'risk_scores', ['tenant_id', 'name', 'risk_type', 'date'], unique=True)
    op.create_index(op.f('ix_risk_scores_tenant_id'), 'risk_scores', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_scores_tenant_id'), table_name='risk_scores')
    op.drop_index('ix_risk_dedup', table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index('ix_pds_tenant_date_name', table_name='participant_daily_stats')
    op.drop_index(op.f('ix_participant_daily_stats_tenant_id'), table_name='participant_daily_stats')
    op.drop_table('participant_daily_stats')
    op.drop_index(op.f('ix_ai_reports_tenant_id'), table_name='ai_reports')
    op.drop_index('ix_ai_report_type_date', table_name='ai_reports')
    op.drop_table('ai_reports')
    # ### end Alembic commands ###
